version: '3'

services:
  resnet_tensorrt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "8080:8080"
    volumes:
      - ./keys:/usr/src/app/keys
    depends_on:
      - resnet_tensorrt
