version: '3.8'

services:
  core_logic_service:
    build: ./core_logic_service
    ports:
      - "5000:5000"
    networks:
      - inference_network

  pytorch_inference_service:
    build: ./pytorch_inference_service
    ports:
      - "5001:5000"
    networks:
      - inference_network
    depends_on:
      - core_logic_service

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - inference_network

  tests:
    build:
      context: ./core_logic_service
      dockerfile: Dockerfile.tests
    networks:
      - inference_network
    depends_on:
      - core_logic_service
      - redis

networks:
  inference_network:
