# Dockerfile.tests
FROM python:3.9
WORKDIR /app
COPY core_logic_service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest
COPY core_logic_service/app /app
COPY core_logic_service/tests /app/tests
COPY core_logic_service/config.py /app
CMD ["pytest", "/app/tests"]

